name: Feature Request
description: Suggest a new feature or enhancement for the FAID Quantum Web App
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below to help us understand your idea.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: Describe your feature idea...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: How would you like this feature to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: Describe any alternative solutions or workarounds you've considered...

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: Which area of the app does this feature relate to?
      options:
        - Data Collection
        - User Interface
        - Performance
        - Security
        - Documentation
        - Integration
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - High - Essential for my workflow
        - Medium - Would significantly improve my work
        - Low - Nice to have
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a specific use case or scenario where this feature would be helpful.
      placeholder: For example, when I'm working on...

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, screenshots from other apps, or links to examples.
      placeholder: Drag and drop images here or paste links...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or information about the feature request here.
      placeholder: Any additional details that might help us understand your request...

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm the following before submitting.
      options:
        - label: I have searched for similar feature requests and didn't find any duplicates
          required: true
        - label: I have provided all the required information above
          required: true
